spring.application.name=api-pokemon-soap
spring.external.rest.url=https://pokeapi.co/api/v2/pokemon/
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
springdoc.swagger-ui.path=/swagger-ui.html
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.request-log-topic=${KAFKA_REQUEST_LOG_TOPIC:request-log-topic}
